#
###################################
# Site wide configuration
####################################
#
title: Nghi Nguyen
email: nghi.dcg@gmail.com
description: Xin chào! Đây là blog của Nghị. Blog cá nhân chia sẻ kiến thức, trải nghiệm và chuyện nghề nghiệp lĩnh vực công nghệ.
url: https://nghi.blog # the base hostname & protocol for your site
keywords: ["mobile app", "frontend", "web development"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Ho_Chi_Minh
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Nghi Nguyen
  avatar: nghi-logo.png
  job: "Co-founder Nepbean Technology, jotodi"
  bio: "Xin chào! Đây là blog của Nghị.<br/>Nghị đang là một Team Leader \"culi\",  sống và làm việc tại TP. Hồ Chí Minh ...<br/><a href=\"/resume/\" title=\"Resume\">XEM CHI TIẾT</a>"
  email: nghi.dcg@gmail.com
  disqus-shortname: nghixn
  twitter: nghixn #username
  facebook: nghixn #username
  google:
    plus: #username
    analytics: UA-111732221-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nghixn #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: nghinx #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
